### ISSUE TITLE
Testing setItem() does not trigger promise

### ISSUE THREAD

**Issue by niant** [scotttrinh/angular-localForage#27]
I noticed while writing unit tests that setItem() doesn't trigger the promise in tests. If I add $rootScope.$apply(); after resolve function it'll work though, but it's in the $localForage code so I'm out of luck. Do you prefer some other way of doing it or can this be fixed somehow?

Reasoning behind $rootScope.$apply(); with unit tests:
https://docs.angularjs.org/api/ng/service/$q#differences-between-kris-kowal-s-q-and-q

**Comment by tlvince** [comment]
@rudijs, @ocombe, manually invoking `angular.injector` solved a similiar issue for me with third-party promises wrapped with `$q.when` not resolving in specs. Out of curiosity, did you ever find out why it works?

**Comment by ocombe** [comment]
Yes, because I use multiple promises and $apply only trigger one, check out the tests now, I'm using a setInterval to trigger the digests and it works (but it's very dirty)

**Comment by oleduc** [comment]
@ocombe Hey, I ran into the exact same issue as well, however invoking angular.injector manually doesn't cut it. 

In my case the LocalForage promise is the one that doesn't work when testing, but works quite fine in the browser.

Any idea?

**Comment by ocombe** [comment]
Have you checked how I do it in my tests ? I'm using setInterval to trigger multiple digests.

**Comment by david-gang** [comment]
Hi @ocombe ,

Nested promises don't work:
```javascript
   function createOrGetUserArea(areaName ) {
                return $localForage.getItem(areaName).then(function(data) {

                   if(data) {
                       area = data;
                       return area;
                   }
                    else {
                       area = {};
                       return $localForage.setItem(areaName,{}).then(function(){
                           return {};
                       });

                   }
                });


            }
```

If i change it to:

```javascript
   function createOrGetUserArea(areaName ) {
                return $localForage.getItem(areaName).then(function(data) {

                   if(data) {
                       area = data;
                       return area;
                   }
                    else {
                       area = {};

                       $localForage.setItem(areaName,{});

                      return area;

                   }
                });


            }
```

it works. This is incorrect as i have to wait for setitem to finish.

Reading the docu of angular $q https://docs.angularjs.org/api/ng/service/$q it should be possible to return a promise from a promise.

> This method returns a new promise which is resolved or rejected via the return value of the successCallback, errorCallback (unless that value is a promise, in which case it is resolved with the value which is resolved in that promise using promise chaining). It also notifies via the return value of the notifyCallback method. The promise cannot be resolved or rejected from the notifyCallback method.

Is there something which i can do here ?

**Comment by ocombe** [comment]
Hello !
Yes $q isn't optimized for unit tests, I haven't found a "good" way to test nested promises, but I have a hack that works fine. As explained above, I'm using setInterval to trigger multiple digests (you can look into my tests to see how it's done).
If you find a better way to do it, let me know :)

**Comment by midhunadarvin** [comment]
I am facing the same problem as @david-gang has mentioned. Nested Promises are not working.
