### ISSUE TITLE
bower angluar-localforage `config` is undefined

### ISSUE THREAD

**Issue by bahtou** [scotttrinh/angular-localForage#37]
I followed through with the readme by installing both localforage and angular-localforage with `bower`.

I tried bundling both files with browserify and I keep getting the following error in chrome:  

`TypeError: Cannot read property 'config' of undefined`
`at new LocalForageInstance (http://localhost:3000/angular-localforage/dist/angular-localforage.js:57:17)`

Prior to this error I was getting other errors in `localforage` about not being able to find the drivers and the promise library.

Any thoughts?

**Comment by cinder92** [comment]
same issue here! im trying to use it with electron, but is not working! im desesperate! :(

**Comment by ocombe** [comment]
You did include both files and in the right order ?

**Comment by cinder92** [comment]
yes i have
