### ISSUE TITLE
IE error, TypeError: Unable to get property 'config' of undefined or null reference

### ISSUE THREAD

**Issue by kynetiv** [scotttrinh/angular-localForage#49]
Hi,

I'm new to angular and trying to implement localforage. Issue is probably my own ignorance , so my apologies upfront. Storing and getting via localforage all works well in Chrome and Firefox but the problem appears in IE (8-11). Specifically getting the error:

`TypeError: Unable to get property 'config' of undefined or null reference`

 on line 58 of angular-localForage.js 

It appears that the localforage object is not defined as I'm also getting an error (thrown before the error I mentioned above) with the localforage.js lib:

`Object doesn't support this action`

 on line 1778. 

 I saw the previous issue #37 is similar so perhaps this is more of an issue for the localforage.js project? 

Thanks for any insights you may provide.

**Comment by andela-idurotola** [comment]
you want to download localforage from MDN and include it in your script before your angular-localforage
in your
