### ISSUE TITLE
ReferenceError: localforage is not defined

### ISSUE THREAD

**Issue by gaecom** [scotttrinh/angular-localForage#8]
i use angular-localForage in service and result in ReferenceError: localforage is not defined

the following is my service code
angular.module('starter.services', ['G','LocalForageModule']). .factory('LoginService',function($http,HOST,$localForage) {
        $localForage.setItem("a",1);
});

**Comment by cinder92** [comment]
i just installed both, angular-localforage and localforage, and i get this issue 

"TypeError: Cannot read property 'config' of undefined
    at new LocalForageInstance (file:///Users/dantecervantes/Documents/Personal/PuntoVenta/js/libs/Storage.js:58:22)"

my index.html has both files in correct directory, wth is going on!? :(

**Comment by ocombe** [comment]
did you include localforage first, then angular localforage ?

**Comment by cinder92** [comment]
yes i have my html like this 

<script type="text/javascript" src="js/libs/angular.min.js"></script>
<script type="text/javascript" src="js/libs/localforage.js"></script>
<script type="text/javascript" src="js/libs/angular-localforage.js"></script>
<script type="text/javascript" src="js/libs/ui-router.js"></script>
<script type="text/javascript" src="js/main.js"></script>
